---
dotfiles_repo: "https://github.com/gvassallo/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - tmux
  - vim
  - tmux.conf
  - zshrc
  - gitconfig
