- name: ansible-role-dotfiles playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: provision
  roles:
  - role: ansible-role-dotfiles
    