---
# setup/install tasks
- include: setup-darwin.yml
  when: ansible_os_family == 'Darwin'
  static: no

- include: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  static: no

- name: Install neovim plugins
  command: nvim "+silent! PluginInstall!" +qall!
