---
# setup/install tasks
- include: setup-darwin.yml
  when: ansible_os_family == 'Darwin'

- include: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install python neovim plugin
  pip:
    name: neovim
    executable: "{{ pip3_name }}"
    state: present
    extra_args: --user

- name: Create .config/nvim directory
  file:
    path: ~/.config/nvim
    state: directory

- name: Link init.vim file
  file:
    src: "{{ dotfiles_repo_local_destination }}/vim/init.vim"
    dest: "~/.config/nvim/init.vim"
    state: link

- name: Install neovim plugins
  command: nvim "+silent! PluginInstall!" +qall!
