---
- name: ubuntu | Add neovim-ppa repository.
  apt_repository: repo='ppa:neovim-ppa/unstable' state=present

- name: ubuntu | Ensure neovim is installed.
  apt: name=neovim state=present

- name: ubuntu | Install python3 dependencies.
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - python3-pip
